use_frameworks!

target 'JJCollectionViewRoundFlowLayout_Swift_Example' do
  pod 'JJCollectionViewRoundFlowLayout_Swift', :path => '../'

  target 'JJCollectionViewRoundFlowLayout_Swift_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
